services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rental
volumes:
  pgdata: